export const INIT = 'INIT'

export const OPEN_SETTINGS = 'OPEN_SETTINGS'
export const CLOSE_SETTINGS = 'CLOSE_SETTINGS'

export const SET_GRID_ROW_HEIGHT = 'SET_GRID_ROW_HEIGHT'

export const SET_DETAIL_PHOTO_REQUEST = 'SET_DETAIL_PHOTO_REQUEST'  // Was: 'SET_CURRENT_SUCCESS'
export const SET_DETAIL_PHOTO_SUCCESS = 'SET_DETAIL_PHOTO_SUCCESS'  // Was: 'FETCH_PHOTO_WORK_SUCCESS'
export const SET_DETAIL_PHOTO_FAILURE = 'SET_DETAIL_PHOTO_FAILURE'
export const CLOSE_DETAIL = 'CLOSE_DETAIL'

export const SET_SELECTED_PHOTOS = 'SET_SELECTED_PHOTOS'  // Was: 'MOVE_HIGHLIGHT_SUCCESS', 'TOGGLE_HIGHLIGHT_SUCCESS', 'SET_HIGHLIGHT_SUCCESS', 'CLEAR_HIGHLIGHT_SUCCESS'
export const SET_LIBRARY_INFO_PHOTO_REQUEST = 'SET_LIBRARY_INFO_PHOTO_REQUEST'
export const SET_LIBRARY_INFO_PHOTO_SUCCESS = 'SET_LIBRARY_INFO_PHOTO_SUCCESS'
export const SET_LIBRARY_INFO_PHOTO_FAILURE = 'SET_LIBRARY_INFO_PHOTO_FAILURE'

export const FETCH_TOTAL_PHOTO_COUNT = 'FETCH_TOTAL_PHOTO_COUNT'
export const FETCH_SECTIONS_REQUEST = 'FETCH_SECTIONS_REQUEST'
export const FETCH_SECTIONS_SUCCESS = 'FETCH_SECTIONS_SUCCESS'  // Was: 'GET_PHOTOS_SUCCESS'
export const FETCH_SECTIONS_FAILURE = 'FETCH_SECTIONS_FAILURE'
export const FETCH_SECTION_PHOTOS = 'FETCH_SECTION_PHOTOS'
export const FORGET_SECTION_PHOTOS = 'FORGET_SECTION_PHOTOS'
export const CHANGE_PHOTOWORK = 'CHANGE_PHOTOWORK'  // Was: 'EDIT_PHOTOWORK_CHANGE'
export const CHANGE_PHOTOS = 'CHANGE_PHOTOS'  // Was: 'UPDATED_PHOTO_SUCCESS'
export const EMPTY_TRASH = 'EMPTY_TRASH'  // Was: 'ON_REMOVED_PHOTOS'

export const SET_IMPORT_PROGRESS = 'SET_IMPORT_PROGRESS'  // Was: 'SET_IMPORT_PROGRESS'

export const FETCH_TAGS = 'FETCH_TAGS'  // Was: 'GET_TAGS_SUCCESS'
export const SET_PHOTO_TAGS = 'SET_PHOTO_TAGS'  // Was: 'CREATE_TAGS_SUCCESS'

export const INIT_DEVICES = 'INIT_DEVICES'  // Was: 'INIT_DEVICES_SUCCESS'
export const ADD_DEVICE = 'ADD_DEVICE'  // Was: 'ADD_DEVICE_SUCCESS'
export const REMOVE_DEVICE = 'REMOVE_DEVICE'  // Was: 'REMOVE_DEVICE_SUCCESS'

export const OPEN_DIFF = 'OPEN_DIFF'
export const CLOSE_DIFF = 'CLOSE_DIFF'

export const OPEN_EXPORT = 'OPEN_EXPORT'  // Was: 'OPEN_EXPORT'
export const CLOSE_EXPORT = 'CLOSE_EXPORT'  // Was: 'CLOSE_EXPORT'

export const TOGGLE_DIFF = 'TOGGLE_DIFF'  // Was: 'TOGGLE_DIFF_SUCCESS'
