export const SETTINGS_EXISTS_REQUEST = 'SETTINGS_EXISTS_REQUEST'
export const SETTINGS_EXISTS_SUCCESS = 'SETTINGS_EXISTS_SUCCESS'
export const SETTINGS_EXISTS_FAILURE = 'SETTINGS_EXISTS_FAILURE'  // Was: 'SETTINGS_EXISTS_ERROR'

export const SET_DETAIL_PHOTO_REQUEST = 'SET_DETAIL_PHOTO_REQUEST'  // Was: 'SET_CURRENT_SUCCESS'
export const SET_DETAIL_PHOTO_SUCCESS = 'SET_DETAIL_PHOTO_SUCCESS'  // Was: 'FETCH_PHOTO_WORK_SUCCESS'
export const SET_DETAIL_PHOTO_FAILURE = 'SET_DETAIL_PHOTO_FAILURE'
export const CLOSE_DETAIL = 'CLOSE_DETAIL'

export const SET_HIGHLIGHTED_PHOTOS = 'SET_HIGHLIGHTED_PHOTOS'  // Was: 'MOVE_HIGHLIGHT_SUCCESS', 'TOGGLE_HIGHLIGHT_SUCCESS', 'SET_HIGHLIGHT_SUCCESS', 'CLEAR_HIGHLIGHT_SUCCESS'

export const FETCH_PHOTOS_REQUEST = 'FETCH_PHOTOS_REQUEST'
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS'  // Was: 'GET_PHOTOS_SUCCESS'
export const FETCH_PHOTOS_FAILURE = 'FETCH_PHOTOS_FAILURE'
export const CHANGE_PHOTOWORK = 'CHANGE_PHOTOWORK'  // Was: 'EDIT_PHOTOWORK_CHANGE'
export const CHANGE_PHOTOS = 'CHANGE_PHOTOS'  // Was: 'UPDATED_PHOTO_SUCCESS'
export const EMPTY_TRASH = 'EMPTY_TRASH'  // Was: 'ON_REMOVED_PHOTOS'

export const START_IMPORT = 'START_IMPORT'  // Was: 'SET_IMPORT'
export const SET_IMPORT_PROGRESS = 'SET_IMPORT_PROGRESS'  // Was: 'SET_IMPORT_PROGRESS'

export const FETCH_DATES = 'FETCH_DATES'  // Was: 'GET_DATES_SUCCESS'

export const FETCH_TAGS = 'FETCH_TAGS'  // Was: 'GET_TAGS_SUCCESS'
export const CREATE_TAGS = 'CREATE_TAGS'  // Was: 'CREATE_TAGS_SUCCESS'

export const INIT_DEVICES = 'INIT_DEVICES'  // Was: 'INIT_DEVICES_SUCCESS'
export const ADD_DEVICE = 'ADD_DEVICE'  // Was: 'ADD_DEVICE_SUCCESS'
export const REMOVE_DEVICE = 'REMOVE_DEVICE'  // Was: 'REMOVE_DEVICE_SUCCESS'

export const OPEN_TAGS_EDITOR = 'OPEN_TAGS_EDITOR'
export const CLOSE_TAGS_EDITOR = 'CLOSE_TAGS_EDITOR'

export const OPEN_DIFF = 'OPEN_DIFF'
export const CLOSE_DIFF = 'CLOSE_DIFF'

export const OPEN_EXPORT = 'OPEN_EXPORT'  // Was: 'OPEN_EXPORT'
export const CLOSE_EXPORT = 'CLOSE_EXPORT'  // Was: 'CLOSE_EXPORT'

export const TOGGLE_DIFF = 'TOGGLE_DIFF'  // Was: 'TOGGLE_DIFF_SUCCESS'
