export const INIT = 'INIT'

export const SET_WEB_GL_SUPPORT = 'SET_WEB_GL_SUPPORT'
export const SET_DEVICE_PIXEL_RATIO = 'SET_DEVICE_PIXEL_RATIO'
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const OPEN_SETTINGS = 'OPEN_SETTINGS'
export const SET_SETTINGS = 'SET_SETTINGS'
export const CLOSE_SETTINGS = 'CLOSE_SETTINGS'

export const SET_GRID_ROW_HEIGHT = 'SET_GRID_ROW_HEIGHT'

export const SET_DETAIL_PHOTO = 'SET_DETAIL_PHOTO'
export const FETCH_DETAIL_PHOTO_DATA_REQUEST = 'FETCH_DETAIL_PHOTO_DATA_REQUEST'
export const FETCH_DETAIL_PHOTO_DATA_SUCCESS = 'FETCH_DETAIL_PHOTO_DATA_SUCCESS'
export const FETCH_DETAIL_PHOTO_DATA_FAILURE = 'FETCH_DETAIL_PHOTO_DATA_FAILURE'
export const CLOSE_DETAIL = 'CLOSE_DETAIL'

export const SET_SELECTED_PHOTOS = 'SET_SELECTED_PHOTOS'
export const SET_LIBRARY_INFO_PHOTO_REQUEST = 'SET_LIBRARY_INFO_PHOTO_REQUEST'
export const SET_LIBRARY_INFO_PHOTO_SUCCESS = 'SET_LIBRARY_INFO_PHOTO_SUCCESS'
export const SET_LIBRARY_INFO_PHOTO_FAILURE = 'SET_LIBRARY_INFO_PHOTO_FAILURE'

export const FETCH_TOTAL_PHOTO_COUNT = 'FETCH_TOTAL_PHOTO_COUNT'
export const FETCH_SECTIONS_REQUEST = 'FETCH_SECTIONS_REQUEST'
export const FETCH_SECTIONS_SUCCESS = 'FETCH_SECTIONS_SUCCESS'
export const FETCH_SECTIONS_FAILURE = 'FETCH_SECTIONS_FAILURE'
export const FETCH_SECTION_PHOTOS = 'FETCH_SECTION_PHOTOS'
export const FORGET_SECTION_PHOTOS = 'FORGET_SECTION_PHOTOS'
export const CHANGE_PHOTOWORK = 'CHANGE_PHOTOWORK'
export const CHANGE_PHOTOS = 'CHANGE_PHOTOS'
export const EMPTY_TRASH = 'EMPTY_TRASH'

export const SET_IMPORT_PROGRESS = 'SET_IMPORT_PROGRESS'

export const FETCH_TAGS = 'FETCH_TAGS'
export const SET_PHOTO_TAGS = 'SET_PHOTO_TAGS'

export const INIT_DEVICES = 'INIT_DEVICES'
export const ADD_DEVICE = 'ADD_DEVICE'
export const REMOVE_DEVICE = 'REMOVE_DEVICE'

export const OPEN_DIFF = 'OPEN_DIFF'
export const CLOSE_DIFF = 'CLOSE_DIFF'

export const OPEN_EXPORT = 'OPEN_EXPORT'
export const CLOSE_EXPORT = 'CLOSE_EXPORT'
export const SET_EXPORT_OPTIONS = 'SET_EXPORT_OPTIONS'
export const TOGGLE_SHOW_EXPORT_REMOVE_INFO_DESC = 'TOGGLE_SHOW_EXPORT_REMOVE_INFO_DESC'
export const SET_EXPORT_PROGRESS = 'SET_EXPORT_PROGRESS'
